Hw 1
onevoker/LinkTrackerBot pull request #1
Opened 2024-02-13 20:31 UTC by onevoker

2024-02-15 19:34 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/ListCommand.java
> +        }
лучше использовать какую-нибудь либку типа Joiner, либо вынести эту логику в новую приватную функцию:
`
private String getLinksListText(Collection<URI> links) {
    ...
}
`

2024-02-15 22:34 UTC, onevoker commented on bot/src/main/java/edu/java/bot/commands/ListCommand.java
> +        }
Вынес логику в приватную функцию, после коммита у меня почему-то в классе LinkTest упал тест testCorrectUri, локально у меня все тесты проходят, не могу понять в чем проблема, я пока на этот тест поставил @Disabled

2024-02-15 22:36 UTC, onevoker commented on bot/src/main/java/edu/java/bot/commands/ListCommand.java
> +        }
Вынес логику в приватную функцию, после коммита у меня почему-то в классе LinkTest упал тест testCorrectUri, локально у меня все тесты проходят, не могу понять в чем проблема, я пока этот тест отключил

2024-02-17 13:54 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/Link.java
> +    private static boolean isGitHubOrStackOverflowLink(String link) {
лучше назвать по типу `isValidReource`
при добавлении новых источников, названия функции тоже менять придется иначе)

2024-02-17 13:58 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/Link.java
> +public class Link {
Я бы подумал в сторону реализации ссылки, как модели, котора бы  в себе хранило строковое представление или `URI`. Проверки на валидность можно сделать прям в конструкторе с выбросом исключения. Либо отдельно сделать метод `validate`  или `checkValidity` или `isValid` или `Optional<Link> takeIfValid()`.

Если все-таки предпочтешь оставить утилитарный класс со статическими методами, то назвать надо соответственно `LinkUtils`, `LinkChecker` и т.п.

2024-02-17 14:00 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/UserLinks.java
> +        if (!set.isEmpty()) {
проверку делать необязательно, если элемента в сете нет, `remove` просто вернет `false`

2024-02-17 14:03 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/UserLinks.java
> +public class UserLinks {
naming: можно назвать `LinksRepository`

Подробнее про паттерн репозиторий:
https://habr.com/ru/articles/248505/

2024-02-17 14:07 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/UserLinks.java
> +    public boolean isRegistered(User user) {
лучше разнести фунциональность по пользователям и ссылкам в отдельные классы

```java
class UserRepository {
    // user-id: user
    private Map<Integer, User> users; // или Set<User> users и переопределение equals и hashcode в User
}

class LinkRepository {
    private Map<Ingteger, Link> links; // или опять же Set<Link>
}

```
При этом сам класс Link тогда должен будет содержать user-id в себе

2024-02-17 14:08 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/UserLinks.java
> +    public boolean isRegistered(User user) {
Но это сложновато может быть, просто в будуших домашках придется разносить все равно, можешь пока так оставить)

2024-02-17 14:10 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/UserLinks.java
> +        } catch (URISyntaxException e) {
так делать не стоит)
потом будет непонятно, в чем конкретно ошибка. Исключения должны явно указывать на то, что пошло не так.
Если не хочешь пробрасывать check excception, можешь создать свой класс, который будет наследоваться от `RuntimeException` и назвать как-то типа `InvalidLinkException`

2024-02-17 14:14 UTC, iskanred commented on bot/src/main/java/edu/java/bot/processor/UserMessageProcessorImpl.java
> +        return List.of(
Тут list каждый раз заново создается при кажом вызове? Можно ли его хранить, как поле для инстанса `UserMessageProcessorImpl`?

2024-02-17 14:14 UTC, iskanred commented on bot/src/main/resources/application.yml
> +  telegram-token: ${tg-token}
✅

2024-02-17 14:15 UTC, iskanred commented on bot/src/test/java/bot/commandsTest/HelpCommandTest.java
> +    @ExtendWith(MockitoExtension.class)
Не встречал такой записи) Это равносильно тому, чтобы над классом аннотацю поставить? Если да, то лучше над классом

2024-02-17 14:17 UTC, iskanred commented on bot/src/test/java/bot/commandsTest/HelpCommandTest.java
> +    void testDescription() {
тест немного избыточный, он просто проверяет, что поле в классе дейтсвительно равно тому, что там написано

если описание будут менять, то и тест придется менять, и смысла в тесте становится немного

2024-02-17 14:19 UTC, iskanred commented on bot/src/test/java/bot/commandsTest/HelpCommandTest.java
> +    private void setUpTest() {
поскольку функция используется только в одном тесте, то лучше прям так и внести ее тело в этот тест

Когда смотришь на тесты, хочется понимать три вещи:
1) Какое окружение конкретно для этого теста было настроено (что замокировано, что хотим возвращать)
2) Что проверям? - Вызов самого метода
3) Как проверяем? - Сранвниваем expected с actual значениями

2024-02-17 14:22 UTC, iskanred commented on bot/src/test/java/bot/commandsTest/TrackCommandTest.java
> +    private void setUpTest(String returnedTextFromMessage) {
Тут `setUptTest` уже нужно больше, чем для одного теста. Но исходя из названии функции непонятно, что оно сетапит и почему не для всех тестов используется.

Лучше назвать функцию более конкретно и показать в названии, что делает.

2024-02-17 14:23 UTC, iskanred commented on bot/src/test/java/bot/commandsTest/UntrackCommandTest.java
> +    private static final User USER = new User(-10L);
Магические числа
Лучше подибрать числа норнмальные, либо относящиеся к corner cases (-1, 0, 1, 99 и пр.)

2024-02-17 14:26 UTC, iskanred commented
Круто сделал! Нравится твоя архитектура! Комменты добавил, они не критичные и на текущую оценку не влияют. Но хочется видеть исправления в дальнейших домашках либо аргументы, почему исправлять не стоит.

В общем классно постарался, 8/8 💯

2024-02-17 16:40 UTC, onevoker commented on bot/src/main/java/edu/java/bot/links/UserLinks.java
> +public class UserLinks {
Не знал к какому комментарию прикрепить данный вопрос, поэтому прикрепил к этому) Я начал исправлять недочеты и снова вылазит ошибка билда, не понимаю почему, но на гитхабе один тест не проходит, который в классе LinkTest(testCorrectUri), хотя локально тест проходит. Можете подсказать, что с этим делать, пожалуйста.

2024-02-17 21:20 UTC, onevoker commented on bot/src/main/java/edu/java/bot/links/UserLinks.java
> +        } catch (URISyntaxException e) {
Может лучше будет поставить аннотацию SneackyThrows, просто в данном методе никогда не будет выброшено исключение, потому что этому классу уже передаются проверенные через Link.isCorrectUri(String link) ссылки, а сам метод просто обрезает лишние слеши в конце ссылки, если вдруг пользователь передаст по сути одинаковые ссылки, но в конце одной из них поставит ,,/,, или например ,,///,,

2024-02-17 21:28 UTC, onevoker commented
Я начал исправлять недочеты и у меня снова вылезла ошибка билда, проблема была в классе LinkTest в тесте testCorrectUri. Локально у меня тест проходит, а на гитхабе он падает на ссылках со stackoverflow. Не понимаю, почему так происходит, помогите, пожалуйста)

2024-02-18 00:13 UTC, iskanred commented
> Я начал исправлять недочеты и у меня снова вылезла ошибка билда, проблема была в классе LinkTest в тесте testCorrectUri. Локально у меня тест проходит, а на гитхабе он падает на ссылках со stackoverflow. Не понимаю, почему так происходит, помогите, пожалуйста)

после проверки дз могу не увидеть, что ты в гихабе написал, лучше можешь сходить с вопросом в личку телеги

2024-02-18 00:17 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/UserLinks.java
> +        } catch (URISyntaxException e) {
можешь sneakyThrows попробовать

ну как минимум точно стоит хотя бы коммент оставить, почему ты бросаешь `RuntimeException`, а еще лучше указать в документации к методу, потому что, например, я сходу не понял, видишь, пришлось уточнять, тратить время)

2024-02-18 14:34 UTC, iskanred commented on bot/src/main/java/edu/java/bot/processor/UserMessageProcessorImpl.java
> +            if (response != null && response.startsWith(command.command())) {
Вдруг в дальнейшем появятся команды с одинаковым префексом? Лучше развить проверку

2024-02-19 18:38 UTC, iskanred commented on bot/src/main/java/edu/java/bot/processor/UserMessageProcessorImpl.java
> +        String strCommand = responseArr[0];
массив заводить в отдельную переменную класть необязательно, можно просто
```
String inputCommand = response.split(" ")[0];
```

2024-02-19 18:45 UTC, iskanred requested changes
Оставил комменты, посылаю запрос на доработку

2024-02-19 18:45 UTC, iskanred commented on bot/src/main/java/edu/java/bot/processor/UserMessageProcessorImpl.java
> +        String strCommand = responseArr[0];
массив заводить в отдельную переменную класть необязательно, можно просто

```java
String inputCommand = response.split(" ")[0];
```

p.s. имя strCommand не очень информативное

2024-02-19 18:45 UTC, iskanred commented on bot/src/main/java/edu/java/bot/processor/UserMessageProcessorImpl.java
> +            if (Objects.equals(strCommand, command.command())) {
можно же сравнить просто
```java
s1.equals(s2)
```

2024-02-19 19:27 UTC, onevoker commented on bot/src/main/java/edu/java/bot/processor/UserMessageProcessorImpl.java
> +            if (Objects.equals(strCommand, command.command())) {
✅

2024-02-19 21:50 UTC, iskanred approved these changes
💯

2024-02-20 11:13 UTC, merged