Hw2
onevoker/LinkTrackerBot pull request #2
Opened 2024-02-23 13:16 UTC by onevoker

2024-02-26 23:16 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/Link.java
> +            return Objects.equals(uri.getHost(), GIT_HUB_DOMAIN)
не задумывался о том, чтобы от Link наследовать классы `GitHubLink` и `StackOverflowLink`? Тогда можно было бы добавлять новый ресурс просто, сделав новый класс и реализовав для него метод `isValidResource()`

сейчас нужно менять реализацию, не очень красиво и нарушает open/close principle из SOLID

2024-02-26 23:16 UTC, iskanred commented on bot/pom.xml
> +            <artifactId>wiremock-standalone</artifactId>
question: зачем в зависимости бота решил добавить wiremock?

2024-02-26 23:36 UTC, iskanred requested changes
🔥 Очень понравилось решение! Здорово продвинулся и правок значительно меньше, чем в прошлый раз. Грамтоно организовал структуру. Видно, что привычные веб-приложения на спринге тебе делать просто, это круто!

💯 6/6! Запрашивай review, как правки внесешь)

2024-02-26 23:36 UTC, iskanred commented on pom.xml
> +                <artifactId>wiremock-standalone</artifactId>
можно добавить только в одноим месте в `scrapper/pom.xml`

2024-02-26 23:36 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/Link.java
> +                || Objects.equals(uri.getHost(), STACK_OVERFLOW_DOMAIN);
не задумывался о том, чтобы от Link наследовать классы `GitHubLink` и `StackOverflowLink`? Тогда можно было бы добавлять новый ресурс просто, сделав новый класс и реализовав для него метод `isValidResource()`

сейчас нужно менять реализацию, не очень красиво и нарушает open/close principle из SOLID

2024-02-26 23:36 UTC, iskanred commented on bot/pom.xml
> +            <artifactId>wiremock-standalone</artifactId>
question: зачем в зависимости бота решил добавить wiremock?

2024-02-26 23:36 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
>  public record ApplicationConfig(
интересная реализация, прикольно сделал)

2024-02-26 23:36 UTC, iskanred commented on scrapper/src/main/java/edu/java/gitHub/dto/RepositoryResponse.java
> +    @JsonProperty("html_url") String htmlUrl,
такие анноташки лучше ставить над параметром, а то приходится глазами сильно вправо уходить, чтобы увидеть название и тип параметра

2024-02-26 23:36 UTC, iskanred commented on scrapper/src/main/java/edu/java/gitHub/dto/RepositoryResponse.java
> +public record RepositoryResponse(
здорово используешь рекорды!  🔥

2024-02-26 23:36 UTC, iskanred commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{scheduler.interval()}")
question: проверял? работает?

2024-02-26 23:36 UTC, iskanred commented on scrapper/src/main/java/edu/java/stackOverflow/client/StackOverflowClient.java
> +            .uri(questionId + "?order=desc&sort=activity&site=stackoverflow")
можно использовать queryParam
```java
webClient.get()
  .uri(uriBuilder - > uriBuilder
    .path("...")
    .queryParam("order", "desc")
    .queryParam("sort", "activity")
    .queryParam("...", "...")
    .build()
```

2024-02-27 10:18 UTC, onevoker commented on pom.xml
> +                <artifactId>wiremock-standalone</artifactId>
Я смотрел на коммиты вот тут: https://github.com/sanyarnd/java-course-2023-backend-template/commits/master/ И просто перенес изменения

2024-02-27 10:27 UTC, onevoker commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{scheduler.interval()}")
Да, работает
![image](https://github.com/onevoker/LinkTrackerBot/assets/146644496/d7987302-9e12-4bcf-a536-4fd5cbdd95b2)

2024-02-27 16:57 UTC, iskanred requested changes
оставил комменты

2024-02-27 16:57 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/Link.java
> +        this.linkValidatorService = linkValidatorService;
в модели очень нехорошо хранить сервис
модель это просто dumb object или [POJO](https://ru.wikipedia.org/wiki/POJO) . Валидировать лучше в самой factory

2024-02-27 16:57 UTC, iskanred commented on bot/src/main/java/edu/java/bot/links/LinkFactory.java
> +        return new Link(userId, normalizeLink(stringLink), linkValidatorService);
то есть так:
```java
uriValidator.validate(stringLink);
return new Link(userId, normalizeLink(stringLink));
```

а UriValidator выглядел бы так:
```java
@Service
class UriValidator {
    void validate(String uri) { if (isNotCorrectUri(uri)) throw new InvalidUriException() }
}
```

2024-02-28 17:25 UTC, iskanred requested changes
Все отлично! Остались минорные правки

2024-02-28 17:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/processor/UserMessageProcessorImpl.java
> +    private final Command helpCommand;
ты можешь сделать `List<Command> commands` полем. Spring сам заинжектит бины в этот лист)

2024-02-28 17:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/ListCommand.java
> +@Component
Я бы подумал в сторону того, чтобы над всеми командами поставить аннотацию `@Service` и переимновать классы в `*CommandService`. По факту, это сервисный слой, который выполняет основную бизнес-логику бота. А просто Command звучит просто как моделька

2024-02-28 19:06 UTC, onevoker commented on bot/src/main/java/edu/java/bot/processor/UserMessageProcessorImpl.java
> +    private final Command helpCommand;
Ого, это прям круто, не знал)

2024-02-28 19:21 UTC, onevoker commented on bot/src/main/java/edu/java/bot/commands/ListCommand.java
> +@Component
Я еще поменял пути в соответствии с шаблоном

2024-02-29 14:33 UTC, iskanred approved these changes
🔥

2024-02-29 14:34 UTC, merged