Hw5
onevoker/LinkTrackerBot pull request #5
Opened 2024-03-16 13:10 UTC by onevoker

2024-03-19 15:57 UTC, iskanred requested changes
🔥 здорово проделанная большая работа!

за дз №5 = 8/8
за бонусное = 14/15, потому что не выполнено требование с выносом jooq кодгена в отдельный модуль

На платформе бонусное дз отправил на доработку

Вообще есть много мелких моментиков, которые было бы неплохо исправить, но вкупе внесение всех правок сильно изменить текущую архитектуру. Если не успеешь исправить все - не страшно, просто с каждой новой домашкой будет тяжелее работать с текущей архитектурой.

На что стоит обратить внимание, если решишься перестроить архитектуру:
* Добавление новго ресурса несет минимальные затраты на добавление и, в особеннности, изменения текущего кода. Т.е. новые DTO, новые сервисы, котроллеры и репозитории - ок. Исправление что-то в существующих - уже красный флажок.
* Стараться по минимуму использовать Util классы и выносить все в сервисы
* Сделать единую систему валидации и получения информации из ссылок. Пришла ссылка, получилось вытащить из нее инфу корректно - кайф, работаем дальше. Не получилось - кладем причину в exception и отправляем боту, как ошибку валидации
* Сосредоточиться на том, какие задачи должен выполнять бот, как интерфейс (валидации ссылок, например), а какие скраппер и постараться логику нигде не дублировать

Это такие основные пукнты 

+ ко всему хочется в комменариях PR увидеть, какие сценарии ты реализовал из бонусной дзшки и чуть их описать, чтобы проверять было удобнее и быстрее)
я вот  до сих пор не уверен, что по коду все сценарии распознал)

Решение с хранением респонсов от сервисов мне понравилось, но хотел бы дополнительного обоснования, зачем оно нужно и почему без этого никак) Для большого кол-ва пользователей хранить все ответы по всем ссылкам будет накладно)

Основной мой поинт, на котором стоит сфокусироваться - увелчить независимость сущностей (классов, методов, модулей), оставив только явные, легко находимые, и легко читаемые и легко понимание зависимости:

Например: сервис зависит от того сервиса, от этих репозиториев и такого-то сервиса. Из обзора зависимостей уже должно складываться впечатление, что он делает даже не глядя на методы. Ровно, как и наоборот, взглянув на сигнатуру методов будет понятно, какие нужны зависимости)

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/linkWorkers/LinkParserUtil.java
> +public class LinkParserUtil {
я бы это в сервис выделил, можно еще возвращать какой-то объект-инфо типа
`GitHubLinkRepoData` или типа такого, где уже лежат поля `owner` и `repo`, все равно используешь их вместе.
Со stackoverflow можно тоже самое для расширяемости

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/linkWorkers/LinkResponseValidatorService.java
> +        boolean isValidResource = isValidResource(url);
нет особого смысла выносить в переменную, тем более, которая называется точно также, как и метод)

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/linkWorkers/LinkResponseValidatorService.java
> +                    .exchangeToMono(response -> Mono.just(response.statusCode().value()));
лучше сразу тут поставить в цепочку `.block`)

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/linkWorkers/LinkResponseValidatorService.java
> +    private static final String REGEX_FOR_STACK_OVERFLOW_QUESTION =
немножо путанная логика со всеми regex и валидаторами, возможно, стоит в один сервис вынести, который бы брал инфу как раз из ссылки, а если URL невалидный, бросал бы exception

мб достаточно будет два сервиса, но там regex'ы хранить где-то в пропертях

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/linkWorkers/LinkResponseValidatorService.java
> +                    .exchangeToMono(response -> Mono.just(response.statusCode().value()));
вот этот вообще весь вызов клиента можно выенсти в приватную функцию типа `ping` и если сайт пингуется, то хорошо, если нет, то делаем вывод, что URL не валидный

При этом в будущем было бы неплохо разделять, когда юзер отправил просто кривую ссылку, а когда сайт не работает допустим, в общем юзеру явно отсылать, что отдал нам запрос по его ссылке (404 или 500, например)

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/linkWorkers/LinkResponseValidatorService.java
> +                return code >= SUCCESS_STATUS_CODE && code < BAD_STATUS_CODE;
есть дефолтные enum `HttpStatus` в Spring Web MVC вроде

там где-то даже метода есть типа `is4xx` или `is5xx`

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/linkWorkers/LinkResponseValidatorService.java
> +    }
тут снова высокая связанность получается с ресурсами, если захотим какой-то добавить, то тут тоже придется добавлять новые методы и обновлять старые

первое, что можно сделать, вынести все regex в список и если ссылка попадает под какой-либо regex => она поддерживается нашим сервисом и не нужно будет отдельные методы выделять

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/linkWorkers/LinkParserUtil.java
> +    private static final String REGEX_FOR_QUESTION_ID = "https://stackoverflow\\.com/questions/(\\d+)/([\\w-]+)";
я бы тоже это выносил куда-то в проперти опять же)

причем для удобства как-то так:
```yaml
...
resources:
- github:
     domain: github.com
     regexp:
        ...
- stackoverflow:
    ...

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/scheduler/updaterWorkers/resorceUpdaterService/GitHubUpdaterService.java
> +                }
тут семантически получается, что мы не просто запрашиваем апдейты, а еще и что-то кладем, если его там не было

тогда название метода не совсем отражает реальность и это не очень хорошо.

я б ы убрал добавление в репозиторий и вынес его при создании запроса на отслеживание или в какой-то другой сервис уровнем выше

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/scheduler/updaterWorkers/resorceUpdaterService/GitHubUpdaterService.java
> +    public List<LinkUpdateRequest> getUpdates(List<Link> links) {
странновато выглядит, конечно, что метод `getUpdates` возвращает список запросов)

мб стоит над неймингом подумать или дополнительный data class завести, который потом можно будет в DTO конветнуть

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/domain/repositoriesTest/ChatLinkRepositoryTest.java
> +    @Rollback
`@Rollback` обязательно?

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/domain/repositories/jdbc/JdbcGitHubResponseRepository.java
> +//@Repository
я бы порекомендовал бины оставлять, можно просто автовайрить их в нужное место с помощью `@Qualifier`

Либо можно пойти дальше, указать в конфиге, какую реализацию хочешь иметь, например `jooq.enabled` и дальше к реализации каждого из репозиториев добавлять `@ConditionalOnProperty(value='jooq.enabled')` или даже можно `@ConditionalOnMissingBean`

https://docs.spring.io/spring-boot/docs/1.1.7.RELEASE/api/org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.html
https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/condition/ConditionalOnMissingBean.html

2024-03-19 15:57 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/domain/servicesTest/LinkTrackerServiceTest.java
> +    private ChatRepository chatRepository;
чтобы прогнать тесты для разных реализаций репозиториев, можно эти классы сделать абсрактными и абстрактными сделать поля репозиториев, а дальше два класса-наследника: `Jooq...Test` и `Jdbc...Test`

Ну это так, если захочется)

Можно и лист каждого из репозиториев подтянуть и прогнать каждый тест для каждого значения в листе

2024-03-19 20:41 UTC, onevoker commented
У меня реализованы сценарии:
1) Когда пользователь вводит /unregister мы сначала проверяем, был ли он вообще зарегестрирован, и если да, то удаляем его, вместе со всеми отслеживающимися им ссылками, там был вопрос по неймингу метода deleteNoOneTrackedLinks, то есть он удаляет ссылки, которые никто уже не отслеживает, в методе unregister мы сначала удаляем нашего пользователя вместо со всеми его ссылками в chat_link, но все его ссылки из link мы удалить не можем, поэтому нужно проверить, отслеживает ли кто-то еще ссылки, которые отслеживал пользователь, который удалился, если никто не отслеживает, то можно их спокойно удалять, если кто-то отслеживает, то удалять нельзя

Если про сценарии из бонусного дз, то я реализовывал их 2, реализовывал со стаковерфлоу
1) Когда появлялся новый ответ(answer_count увеличивался), то будет выведено специальное сообщение, то же самое с закрытием вопроса(is_answered) на стаковерфлоу, реализовывал я это через дополнительные таблички для этих запросов, то есть проверил вопрос на стаковерфлоу, взял этот вопрос из бд, если они разные, то проверяем что конкретно разное и исходя из этого формируем наш ответ пользователю
2) Так же добавил каскадное удаление на ссылки, чтобы когда ссылка удалялась из link она так же удалялась и из доп табличек

2024-03-19 20:49 UTC, onevoker commented on scrapper/src/main/java/edu/java/scrapper/clients/GitHubClient.java
> +            .block();
Да, я думаю потом отдельно в каком-то дз перевести на реактивщину

2024-03-19 20:59 UTC, onevoker commented on scrapper/pom.xml
> +        </dependency>
недосмотрел немного)

2024-03-19 21:00 UTC, onevoker commented on scrapper/src/main/java/edu/java/scrapper/domain/services/LinkTrackerService.java
> +            addNoOneTrackedLink(tgChatId, linkUrl);
ну это просто не совсем новая ссылка, то есть у пользователя она может быть новой, но в бд ее уже кто-то может отслеживать или это может быть совершенно новая ссылка, которую никто еще никогда не отслеживал, я поэтому так и назвал

2024-03-19 21:02 UTC, onevoker commented on scrapper/src/main/java/edu/java/scrapper/domain/services/TelegramChatService.java
> +    private void deleteNoOneTrackedLinks(List<Link> links) {
лучше переименовать? Я просто пытался сделать акцент на том, что именно никто их не отслеживает

2024-03-19 21:05 UTC, onevoker commented on scrapper/src/main/java/edu/java/scrapper/dto/gitHubDto/RepositoryResponse.java
> +public class RepositoryResponse {
я использую BeanPropertyRowMapper для преобразования данных с бд в jdbc, когда у меня были рекорды, то он не мог преобразовать, поэтому решил просто напрямую переделать рекорды в классы и добавить им Data, чтобы не писать свои мапперы

2024-03-19 21:23 UTC, onevoker commented on scrapper/src/main/java/edu/java/scrapper/domain/repositories/jdbc/JdbcChatLinkRepository.java
> +    public void add(ChatLink chatLink) {
Да, она избыточная, поправил

2024-03-19 22:16 UTC, onevoker commented on scrapper/src/main/java/edu/java/scrapper/domain/repositories/jdbc/JdbcGitHubResponseRepository.java
> +//@Repository
Да, я думал о реализации выбора репозиториев, но потом увидел, что это одно из заданий в 6 дз, там можно будет выбрать из JPA, JDBC, JOOQ

2024-03-19 22:19 UTC, onevoker commented on scrapper/src/test/java/edu/java/scrapper/domain/servicesTest/LinkTrackerServiceTest.java
> +    private ChatRepository chatRepository;
Потом можно будет выбрать(в 6м дз) какие бины создаются, при этом мне тесты не нужно будет менять, поэтому я решил реализовать вот так

2024-03-19 22:37 UTC, onevoker commented on scrapper/src/test/java/edu/java/scrapper/domain/repositoriesTest/ChatLinkRepositoryTest.java
> +    @Rollback
Нет, используя Transactional в тестах будет автоматически выполнен потом Rollback, я об этом не знал, просто посмотрел на примеры тестов в дз5 и повелся)

2024-03-19 23:14 UTC, onevoker commented on scrapper/src/main/java/edu/java/scrapper/scheduler/updaterWorkers/resorceUpdaterService/GitHubUpdaterService.java
> +                }
Я сделал так, потму что так проще) Если это делать на стадии добавления ссылки в link, то нам нужно еще ее будет прокручивать, определять, это ссылка с гитхаба или стаковерфлоу, какая-та дополнительная логика, а в этих сервисах уже приходят ссылки по необходимым ресурсам и мы сразу знаем как с ними работать

2024-03-20 00:06 UTC, onevoker commented
Я решил хранить респонсы от сервисов, так как так легко будет проверить, что конкретно поменялось, достаточно просто по полям пройтись и добавить по ним сообщения об изменениях, в целом, это как отдельные сущности бд у меня

2024-03-21 02:55 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/domain/services/TelegramChatService.java
> +    private void deleteNoOneTrackedLinks(List<Link> links) {
тогда лучше в комментарие или доке к методу это уточнить)
теперт посыл понятен)

2024-03-25 19:36 UTC, iskanred approved these changes
Вроде хорошо! С валидатором мне прям понравилось!

Можно попробовать такой эксперимент в конце курса - добавить возможность отслеживания нового ресурса. И посмотреть, в скольких местах пришлось менять)

А так вообще аппрув ✅

Понимаю, что некоторые места тяжело исправить. Думаю, дело в том, что у вас изначально не было общейк картины, как будет выглядеть приложение, чтобы можно было с самого начала закладываться в архитектуру. Но на то это и учебный курс)

2024-03-25 19:36 UTC, iskanred commented on bot/src/main/java/edu/java/bot/linkValidators/LinkResponseValidatorService.java
> +        return false;
я бы сделал так:
```java
if (!isValidResource(url)) {
   return false;
}
pingLink();
return true;
```

2024-03-25 19:36 UTC, iskanred commented on bot/src/main/java/edu/java/bot/linkValidators/LinkResponseValidatorService.java
> +        return false;
https://habr.com/ru/articles/348074/

2024-03-25 21:12 UTC, merged