Hw6
onevoker/LinkTrackerBot pull request #6
Opened 2024-03-23 21:48 UTC by onevoker

2024-03-28 23:28 UTC, iskanred requested changes
Мощно! 🔥

8/8 💯

Подумай про мапу! Интересная мысль вроде. Позволит еще лушче масштабироваться и проще доабвлять новый ресурс)

2024-03-28 23:28 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/domain/repositories/jpa/JpaChatLinkRepository.java
> +    public int remove(ChatLink chatLink) {
можешь boolean лушче возвращать тогда?

2024-03-28 23:28 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/scheduler/updaterWorkers/LinkUpdaterService.java
> +            return List.of();
мб знаешь, есть еще такая штука:
```java
Collections.emptyList()
```

2024-03-28 23:28 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/scheduler/updaterWorkers/LinkUpdaterService.java
> +            }
такое поведение, как будто хорошо в мапу выносится Map<String, List<Link>>

а вообще даже не так, а вот так:
```java
...
private Map<String, LinkUpdaterService> domainToLinkUpdates;
...

interface LinkUpdaterService {
    LinkUpdateResponse update(); // над неймингом еще подумать, но кажется `get обычно используют для простого геттера
}

class GitHubLinkUpdaterService { ... }
class StackOverflowLinkUpdaterService { ... } 
...
```
т.е. мапа получается такой:
domain -> update service

2024-03-28 23:28 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/scheduler/updaterWorkers/LinkUpdaterService.java
> +            }
т.е, сделать трюк, который мы с командами провернули - лист бинов апдейтеров заполнит спринг, а мы это развернем в мапу

Можно хранить название домена в этом сервисе, получая его из пропертей

2024-03-28 23:28 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +@SpringBootTest
Почему тут тебе эта аннотация понадобилась?)

Она сейчас у тебя весь контекст спринга поднимает, т.к. создает все бины. В анноташке можно указать, какие именно бины тебе понадобятся. Но вообще интересно, зачем тебе аннотация над абстрактным классом понадобилась.

2024-03-28 23:28 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/domain/servicesTest/TelegramChatServiceTest.java
> +    @Transactional
аннотацию можно на уровень класса вынести, т.к. все методы ей обладают

2024-03-29 08:48 UTC, onevoker commented on scrapper/src/main/java/edu/java/scrapper/domain/repositories/jpa/JpaChatLinkRepository.java
> +    public int remove(ChatLink chatLink) {
В jdbc и jooq реализациях там возвращается колличество удаленных записей. А имплементят все один и тот же интерфейс. В jpa я сделал просто возвращение 1 при удалении, так как на логику влиет только значение 0 и >0

2024-03-29 08:52 UTC, onevoker commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +@SpringBootTest
Я написал так, чтобы во всех наследующихся тестах не писать SpringBootTest. Я 1 раз в IntegrationTest поднимаю и все

2024-03-30 20:50 UTC, merged