Hw7
onevoker/LinkTrackerBot pull request #7
Opened 2024-03-31 18:31 UTC by onevoker

2024-04-16 22:15 UTC, iskanred requested changes
Все круто выглядит и аккуратно, здорово! 🔥

Я бы, правда, еще добавил тестов на ретрай в клиентах. Хотя бы на кол-во без типа бэкоффа. Главное протестить, что дейтсвительно весь код, который ты написал позволяет делать ретрай на те ошибки, которые получаешь от сервера. У нас так было на проектк, что ретраи не тестили, а в итоге спутся полгода на проде оказалось, что они и не работали, потому что ретраи триггерили напрямую на `ReadTimeoutException` и `ConnectTimeoutException`, хотя экспешены таймаутов были вложены в `WebClientResponseException`)) Логику лучше проверить

Плюс, сейчас все параметры для ретраев у тебя стоят одни для всех клиентов. Хотя разные ресурсы (бот, гитхаб, стэк) могут отвечать с разной скоростью / разными статусами / быть не доступными. В общем лучше сделать так, чтобы можно было параметризировать политику ретраев для каждого клиента. В идеале, если еще и саму политику ретраев можно менять, например, одному ресурсу лучше linear retry, а другому - exponential или jitter. При было бы круто, если бы кол-во кода не возросло линейно. Можно иметь дефолтную родительскую реализацию политики ретраев и менять при необходимости или как-то по-другому сделать. Это необязательно, но было супер и приближенно к реальности!

В реальных проектах параметры ретраев относят к конфигу клиента:
```yaml
some-client:
    base-url: ...
    get-smth:
        url: ${base-url}/smth/
        ...
     retry-policy:
         backoff: 1s
         backoff-type: exponential
```

💯 6/6 но нужно добавить тесты на ретраи, внести минорные правки и подумать в сторону разделения параметров ретраев для разных клиентов (если хочется и есть время)

2024-04-16 22:15 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controllers/filters/RateLimitingFilter.java
> +public class RateLimitingFilter extends OncePerRequestFilter {
у bucket4j есть свой spring boot starter, который можно настроить через yaml конфиг и использовать встроенные аннотации. Так было бы попроще и поприятнее)

https://github.com/MarcGiffing/bucket4j-spring-boot-starter?tab=readme-ov-file#property-configuration-examples

2024-04-16 22:15 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/RetryConfig.java
> +    public Retry retry() {
прикольно, что решил использовать resilience4j!

Чисто для инфо: у WebClient можно тоже гибко настраивать ретраи через Retry и ExchangeFilterFunction. Таким образом, политика ретраев будет вшита в сам клиент без вынеснеия логики ретраев наверх

![image](https://github.com/onevoker/LinkTrackerBot/assets/37081728/69580a9a-8085-4450-88f1-d0e2adbd7e7d)

https://medium.com/@robert.junklewitz/global-webclient-retry-logic-for-all-endpoints-in-spring-webflux-dbbe54206b63

2024-04-16 22:15 UTC, iskanred commented on bot/src/main/java/edu/java/bot/retry/BackOfType.java
> +public enum BackOfType {
а зачем хранить енам? где используется?

кстати, `Backoff`, а не `BackOf`)

2024-04-17 17:41 UTC, merged

2024-04-18 15:49 UTC, onevoker commented
Исправил в pr HW9