Hw9
onevoker/LinkTrackerBot pull request #9
Opened 2024-04-13 18:37 UTC by onevoker

2024-04-13 18:45 UTC, onevoker commented
### **### Task 1:**
Метрики scrapper
![image](https://github.com/onevoker/LinkTrackerBot/assets/146644496/7294b455-d042-4a64-bc7e-2b02af33875a)
Метрики bot
![image](https://github.com/onevoker/LinkTrackerBot/assets/146644496/f01be43b-71e8-4348-a2c4-dbf0e0aaeb7e)
### Task 2:
![image](https://github.com/onevoker/LinkTrackerBot/assets/146644496/acbc622a-e3c5-4828-8a4e-6247edc2b4e9)
### Task 3:
![image](https://github.com/onevoker/LinkTrackerBot/assets/146644496/301cb2bd-ece2-4bc3-967c-a4ff46a08445)
### Task 4:
Метрики bot
![image](https://github.com/onevoker/LinkTrackerBot/assets/146644496/bd8cb654-9a4e-42e3-936f-a480ed7d6e90)
Метрики scrapper
![image](https://github.com/onevoker/LinkTrackerBot/assets/146644496/359145f3-d37e-4ed9-a382-f43844fb176d)
### Task 5:
bot
![image](https://github.com/onevoker/LinkTrackerBot/assets/146644496/a2b3d1ba-31fa-417c-814a-e06c3d812636)
scrapper
![image](https://github.com/onevoker/LinkTrackerBot/assets/146644496/7d6cdffe-8413-4953-839f-f9100f945095)

2024-04-18 21:41 UTC, iskanred requested changes
ДЗ#7 комментарии

2024-04-18 21:41 UTC, iskanred commented on scrapper/src/main/java/edu/java/scrapper/ScrapperApplication.java
> +@EnableConfigurationProperties({ApplicationConfig.class, ResourcesConfig.class})
я бы сдела указание пакета, чтобы при дальнейшем добавлении проперти-классов, не надо было добавлять сюда

2024-04-18 21:41 UTC, iskanred commented on scrapper/src/main/resources/application.yml
> +      httpStatuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT, TOO_MANY_REQUESTS
вообще, кстати, бот это же не ресурс как таковой, а просто клиент

я бы либо вынес его из ресурсов куда-то, либо просто переназвал на `clients`

2024-04-18 21:49 UTC, iskanred requested changes
А тесты для ретрев в боте не стал добавлять?

2024-04-18 21:49 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/retryTest/ConstantRetryTest.java
> +                )
можно параметризировать тест, чтобы прогнать тест на всех статусах

2024-04-18 22:56 UTC, iskanred approved these changes
✅

2024-04-30 20:57 UTC, iskanred approved these changes
Все круто! Максимальный балл 6/6 💯

\+ попилил бы все графики на разные панели, а то вообще ничего не понятно) Разные метрики разных типов, разные величины, размерности, промежутки, поэтмоу все на одном отображать не вариант)

Нужно, чтобы одна панель отвечала за одну метрику (хотя бы по смыслу) и обязательно метрику одного типа (counter, histogram и пр.) - т.е. либо метрика такая должна быть, либо ее надо приводить к этому

2024-04-30 21:14 UTC, merged